services:
  # db:
  #   image: postgres:17.0
  #   environment:
  #     POSTGRES_USER: namans    # Set your PostgreSQL username here
  #     POSTGRES_PASSWORD: aRAY_YAR12!  # Set your PostgreSQL password here
  #     POSTGRES_DB: madmajors        # Name your default database
  #   ports:
  #     - "5432:5432"                    # Maps container port to host port
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data # Volume for data persistence
  
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "5001:5000"
    # depends_on:
    #   - db

  nb:
    build:
      context: .
      dockerfile: nb.Dockerfile
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: ""  # Disable token-based auth
      JUPYTER_PASSWORD: ""  # No password required
    ports:
      - "8888:8888"
    volumes:
      - ./nb:/home/jovyan/work
    # depends_on:
    #   - db
    command: >
      "start-notebook.sh"

# volumes:
#   pgdata:
  
